In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np
data=pd.read_csv("loan_data.csv")     #Here dataset is loaded
data.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
1,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
2,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
3,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
4,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381 entries, 0 to 380
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            381 non-null    object
 1   Gender             376 non-null    object
 2   Married            381 non-null    object
 3   Dependents         373 non-null    object
 4   Education          381 non-null    object
 5   Self_Employed      360 non-null    object
 6   ApplicantIncome    381 non-null    int64
 7   CoapplicantIncome  381 non-null    float64
 8   LoanAmount         381 non-null    float64
 9   Loan_Amount_Term   370 non-null    float64
 10  Credit_History     351 non-null    float64
 11  Property_Area      381 non-null    object
 12  Loan_Status        381 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 38.8+ KB

In [4]:
data["Gender"].unique()

array(['Male', 'Female', nan], dtype=object)

In [5]:
data.isnull().sum()

Loan_ID               0
Gender                5
Married               0
Dependents            8
Education             0
Self_Employed        21
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term     11
Credit_History       30
Property_Area         0
Loan_Status           0
dtype: int64

In [6]:
data["Education"].unique()

array(['Graduate', 'Not Graduate'], dtype=object)

In [7]:
data['Loan_Amount_Term'].unique()

array([360., 120., 240.,  nan, 180.,  60., 300., 480.,  84.,  12.,  36.])

In [8]:
data['Gender'].fillna("Unknown",inplace=True)

In [9]:
data['Self_Employed'].fillna("Unknown",inplace=True)

In [10]:
data.isnull().sum()

Loan_ID               0
Gender                0
Married               0
Dependents            8
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term     11
Credit_History       30
Property_Area         0
Loan_Status           0
dtype: int64

In [11]:
data['Dependents'].unique()

array(['1', '0', '2', '3+', nan], dtype=object)

In [12]:
data['Credit_History'].unique()

array([ 1., nan,  0.])

In [13]:
data['Loan_Amount_Term'].unique()

array([360., 120., 240.,  nan, 180.,  60., 300., 480.,  84.,  12.,  36.])

In [14]:
data['Loan_Amount_Term'].fillna(data['Loan_Amount_Term'].mean(),inplace=True)

In [15]:
data['Dependents'].fillna('Unknown',inplace=True)

In [16]:
data['Credit_History'].fillna(0,inplace=True)

In [17]:
data.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [18]:
data['Credit_History'].values

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 0., 0.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0.,
       1., 1., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 0.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0.,
       1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.,
       0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1.,
       1., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0.,
       1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1.,
       1., 0., 1., 1., 1., 1., 0.])

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381 entries, 0 to 380
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            381 non-null    object
 1   Gender             381 non-null    object
 2   Married            381 non-null    object
 3   Dependents         381 non-null    object
 4   Education          381 non-null    object
 5   Self_Employed      381 non-null    object
 6   ApplicantIncome    381 non-null    int64
 7   CoapplicantIncome  381 non-null    float64
 8   LoanAmount         381 non-null    float64
 9   Loan_Amount_Term   381 non-null    float64
 10  Credit_History     381 non-null    float64
 11  Property_Area      381 non-null    object
 12  Loan_Status        381 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 38.8+ KB

In [20]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data['Education']=le.fit_transform(data['Education'])
data['Property_Area']=le.fit_transform(data['Property_Area'])
data['Loan_Status']=le.fit_transform(data['Loan_Status'])
data.head(10)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001003,Male,Yes,1,0,No,4583,1508.0,128.0,360.0,1.0,0,0
1,LP001005,Male,Yes,0,0,Yes,3000,0.0,66.0,360.0,1.0,2,1
2,LP001006,Male,Yes,0,1,No,2583,2358.0,120.0,360.0,1.0,2,1
3,LP001008,Male,No,0,0,No,6000,0.0,141.0,360.0,1.0,2,1
4,LP001013,Male,Yes,0,1,No,2333,1516.0,95.0,360.0,1.0,2,1
5,LP001024,Male,Yes,2,0,No,3200,700.0,70.0,360.0,1.0,2,1
6,LP001027,Male,Yes,2,0,Unknown,2500,1840.0,109.0,360.0,1.0,2,1
7,LP001029,Male,No,0,0,No,1853,2840.0,114.0,360.0,1.0,0,0
8,LP001030,Male,Yes,2,0,No,1299,1086.0,17.0,120.0,1.0,2,1
9,LP001032,Male,No,0,0,No,4950,0.0,125.0,360.0,1.0,2,1

In [21]:
from sklearn.model_selection import train_test_split
x=data.iloc[:,[4,6,7,8,9,10,11]]
y=data.iloc[:,12]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [22]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [23]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
print("Here 0 means no and 1 means yes!")
y_pred=rf.predict(x_test)
y_pred

Here 0 means no and 1 means yes!

array([1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1])

In [24]:
data.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001003,Male,Yes,1,0,No,4583,1508.0,128.0,360.0,1.0,0,0
1,LP001005,Male,Yes,0,0,Yes,3000,0.0,66.0,360.0,1.0,2,1
2,LP001006,Male,Yes,0,1,No,2583,2358.0,120.0,360.0,1.0,2,1
3,LP001008,Male,No,0,0,No,6000,0.0,141.0,360.0,1.0,2,1
4,LP001013,Male,Yes,0,1,No,2333,1516.0,95.0,360.0,1.0,2,1

In [25]:
education=int(input("Enter your education(graduate=0,not gradudate=1): "))
applicantincome=int(input("Enter the applicant income: "))
coapplicantincome=int(input("Enter the coapplicant income: "))
loanamount=int(input("Enter your loan amount: "))
loanamountterm=int(input("Enter your loan amount term: "))
credithistory=int(input("Enter your credit history(0-1): "))
propertyarea=int(input("Enter your property area(0-2): "))
new_data=[[education,applicantincome,coapplicantincome,loanamount,loanamountterm,credithistory,propertyarea]]
new_data_scaled=sc.transform(new_data)
prediction=rf.predict(new_data_scaled)
print("Your prediction is: ",prediction)
if(prediction==0): 
    print("I am sorry to say, You are not eligible for loan!")
else:
    print("Congratulations!, You are eligible for loan")

Enter your education(graduate=0,not gradudate=1):  0
Enter the applicant income:  44575
Enter the coapplicant income:  35446
Enter your loan amount:  35452
Enter your loan amount term:  12
Enter your credit history(0-1):  0
Enter your property area(0-2):  0

Your prediction is:  [0]
I am sorry to say, You are not eligible for loan!

In [26]:
from sklearn.metrics import (accuracy_score,precision_score,recall_score,f1_score,roc_auc_score,confusion_matrix)
acc=accuracy_score(y_test,y_pred)
print("accuracy score = ",acc)
prec=precision_score(y_test,y_pred)
print("precision score = ",prec)
rec=recall_score(y_test,y_pred)
print("recall score = ",rec)
f1=f1_score(y_test,y_pred)
print("f1 score = ",f1)
auc=roc_auc_score(y_test,y_pred)
print("roc-auc-score = ",auc)
confuse=confusion_matrix(y_test,y_pred)
print("confusion matrix=\n",confuse)

accuracy score =  0.7662337662337663
precision score =  0.7936507936507936
recall score =  0.9090909090909091
f1 score =  0.847457627118644
roc-auc-score =  0.6590909090909091
confusion matrix=
 [[ 9 13]
 [ 5 50]]